//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedbacksystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FeedBackSystemEntities2 : DbContext
    {
        public FeedBackSystemEntities2()
            : base("name=FeedBackSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Feedback_tbl> Feedback_tbl { get; set; }
        public virtual DbSet<Question_tbl> Question_tbl { get; set; }
    }
}
